#!/usr/bin/env bash

function help {
    cat <<EOF

Para incluir un dominio, es necesario que aproveas:

    - tipo: el tipo de código usado. Por ejemplo: php, cakephp, codeigniter, zendframework, etc. (3 o más chars)
    - dominio: un dominio completo. Por ejemplo: ejemplo.com, ejemplo.org, ejemplo.net (6 o más chars)

separado por un espacio cada uno.

Ejemplo:
    
    [root@web1 ~]# ${0} php ejemplo.com

Inténtalo de nuez.

EOF
}

if (( ${#1} < 3 )) || (( ${#2} < 6 )); then 
    cat <<EOF

    Te recuerdo el formato que debes seguir... más atención! No son palomitas lo que estás haciendo!
EOF

    help
    
    exit 1
elif [[ -f /etc/httpd/vhost.d/live/${2}.conf ]]; then
    cat <<EOF

    El virtual host para ${2} ya ha sido creado, imbeciloide!
EOF
    help

    exit 2
fi

while read t d; do
   cat <<EOF > /etc/httpd/vhost.d/live/${d}.conf
<VirtualHost *:80>
    DocumentRoot /var/www/${t}/${d}/default
    ServerName ${d}
    ServerAlias www.${d}

    <Directory /var/www/${t}/${d}/default>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride Options FileInfo Limit
        Order Deny,Allow 
        Allow from all
        Deny from none
    </Directory>
</VirtualHost>

EOF

done < <( echo $1 $2 )

exit 0
