#!/usr/bin/env bash

function help () {
    cat <<EOF

Para incluir un subdominio, es necesario que ya exista el dominio y que aproveas:

    - tipo: el tipo de código usado. . Por ejemplo: php, cakephp, codeigniter, zendframework, etc. (3 o más chars)
    - dominio: un dominio completo. Por ejemplo: ejemplo.com, ejemplo.org, ejemplo.net, etc. (6 o más chars)
    - subdominio: un subdominio. Por ejemplo: descargas, video, secure, etc. (1 o más chars)

separado por un espacio cada uno.

Ejemplo:
    
    [root@web1 ~]# ${0} php ejemplo.com intranet

Inténtalo de nuez.

EOF
}

if (( ${#1} < 3 )); then
    echo 'Error: el tipo no es válido: ' $1
    help
    exit 1
elif (( ${#2} < 6 )); then
    echo 'Error: el dominio no es válido: ' $2
    help
    exit 2
elif [[ -z $3 ]]; then
    echo 'Error: el subdominio no es válido: ' $3
    help
    exit 3
elif [[ ! -f /etc/httpd/vhost.d/live/${2}.conf ]]; then
    echo 'Error: el dominio no existe todavía: ' $2
    help
    exit 4
elif ( grep -i ${3}.${2} <( httpd -S ) &> /dev/null ); then
    echo 'Èrror: el subdominio ya existe: ' ${3}.${2}
    exit 5
fi

while read t d s; do
   cat <<EOF >> /etc/httpd/vhost.d/live/${d}.conf
<VirtualHost *:80>
    DocumentRoot /var/www/${t}/${d}/${s}
    ServerName ${s}.${d}
    ServerAlias www.${s}.${d}

    <Directory /var/www/${t}/${d}/${s}/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride Options FileInfo Limit
        Order Deny,Allow 
        Allow from all
        Deny from none
    </Directory>
</VirtualHost>

EOF

# create dorectories
echo 'Creando directorios...'
if mkdir /var/www/${t}/${d}/${s} 2> genSub-error.log; then
    echo -n ' OK'
else
    echo -n ' ERROR'
    exit 6
fi

# fix permissions
echo 'Arreglando permisos...'
chown -R apache.webdev /var/www/${t}/${d}/${s}
chmod 2775 /var/www/${t}/${d}/${s}

done < <( echo $1 $2 $3 )

# reload httpd
echo 'Recargando configuración de apache...'
systemctl reload httpd.service

exit 0
